apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextgen-connect.fullname" . }}
  labels:
    {{- include "nextgen-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: mirth
  selector:
    {{- include "nextgen-connect.selectorLabels" . | nindent 4 }}
